language: perl

install:
  - cpanm Clustericious::Config
  - cpanm Clustericious::Log
  - cpanm Hash::Merge
  - cpanm Log::Log4perl::CommandLine
  - cpanm Mojolicious

before_script:
  - perl Build.PL

script: HARNESS_IS_VERBOSE=1 prove -lvr t

perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

