---
abstract: 'Administer clustericious clusters.'
author:
  - 'Brian Duggan <brian.duggan@nasa.gov>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clustericious-Admin
provides:
  Clustericious::Admin:
    file: lib/Clustericious/Admin.pm
    version: 0.19
requires:
  Clustericious::Config: 0
  Clustericious::Log: 0
  Log::Log4perl::CommandLine: 0
  Mojolicious: 2.69
  Term::ANSIColor: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.19
